import fs from 'node:fs';
import path from 'node:path';
import PDFDocument from 'pdfkit';
import { fileURLToPath } from 'node:url';

const backendRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const agreementsDirectory = path.join(backendRoot, 'storage', 'rental-agreements');

const displayDate = (value) => {
  if (!value) return 'Not provided';
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? String(value) : date.toLocaleDateString('en-GB');
};

const displayText = (value) => String(value ?? '').trim() || 'Not provided';

export const generateRentalAgreement = async (rental) => {
  await fs.promises.mkdir(agreementsDirectory, { recursive: true });
  const filename = `rental-agreement-${rental._id}.pdf`;
  const absolutePath = path.join(agreementsDirectory, filename);
  const relativePath = `/applications/${rental._id}/agreement`;

  await new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 56, info: { Title: 'Residential Rental Agreement' } });
    const output = fs.createWriteStream(absolutePath);
    output.on('error', reject);
    doc.on('error', reject);
    output.on('finish', resolve);
    doc.pipe(output);

    doc.font('Helvetica-Bold').fontSize(20).text('RESIDENTIAL RENTAL AGREEMENT', { align: 'center' });
    doc.moveDown(0.4);
    doc.font('Helvetica').fontSize(10).fillColor('#526174')
      .text(`Agreement reference: ${rental._id}`, { align: 'center' });
    doc.moveDown(1.6);
    doc.fillColor('#172033').font('Helvetica')
      .fontSize(11)
      .text('This agreement records the rental request submitted by the tenant. The details below are based on the saved rental application.', {
        align: 'justify',
        lineGap: 4,
      });
    doc.moveDown(1.2);

    const section = (heading, rows) => {
      doc.font('Helvetica-Bold').fontSize(13).fillColor('#173b67').text(heading);
      doc.moveDown(0.4);
      rows.forEach(([label, value]) => {
        doc.font('Helvetica-Bold').fontSize(10).fillColor('#26354a').text(`${label}: `, { continued: true });
        doc.font('Helvetica').fontSize(10).fillColor('#26354a').text(displayText(value), { lineGap: 3 });
      });
      doc.moveDown(0.9);
    };

    section('TENANT DETAILS', [
      ['Full name', rental.userName || rental.fullName],
      ['Email', rental.userEmail || rental.email],
      ['CNIC', rental.cnic],
      ['Phone', rental.userPhone || rental.phone],
    ]);
    section('PROPERTY DETAILS', [
      ['Property', rental.propertyTitle || rental.propertyName],
      ['Property type', rental.propertyType],
      ['Property reference', rental.propertyId],
    ]);
    section('RENTAL TERM', [
      ['From date', displayDate(rental.moveInDate || rental.preferredMoveInDate || rental.fromDate)],
      ['To date', displayDate(rental.rentalEndDate || rental.toDate || rental.endDate)],
      ['Duration', rental.rentalDuration || rental.rentalDurationMonths],
      ['Rent amount', rental.rent || rental.monthlyRent || rental.amount ? `PKR ${Number(rental.rent || rental.monthlyRent || rental.amount).toLocaleString('en-PK')}` : 'Not provided'],
      ['Application status', rental.applicationStatus || rental.status || 'Pending'],
    ]);

    doc.font('Helvetica').fontSize(10).fillColor('#26354a')
      .text('The tenant and property representative may use the spaces below to record their signatures and the date of execution.', {
        align: 'justify',
        lineGap: 4,
      });
    doc.moveDown(2);
    doc.text('Tenant signature: ______________________________', { continued: false });
    doc.moveDown(1.2);
    doc.text('Property representative: _________________________');
    doc.moveDown(1.2);
    doc.text('Date: _________________________________________');

    const footerY = doc.page.height - 42;
    doc.moveTo(56, footerY - 10).lineTo(doc.page.width - 56, footerY - 10).strokeColor('#d9e1eb').stroke();
    doc.font('Helvetica').fontSize(8).fillColor('#687589')
      .text('Generated by RMS Rental Management System. This document reflects the submitted application details.', 56, footerY, {
        width: doc.page.width - 112,
        align: 'center',
      });
    doc.end();
  });

  return { absolutePath, relativePath, filename };
};

export const getRentalAgreementPath = (applicationId) => path.join(
  agreementsDirectory,
  `rental-agreement-${path.basename(String(applicationId))}.pdf`,
);
