import mongoose from 'mongoose';

const rentalProfileSchema = new mongoose.Schema({
  userId: { type: String, required: true, index: true, unique: true },
  fullName: { type: String, required: true },
  email: { type: String, required: true },
  phone: { type: String, default: '' },
  profileImage: { type: String, default: '' },
  dateOfBirth: { type: Date, default: null },
  gender: { type: String, default: '' },
  currentAddress: { type: String, default: '' },
  city: { type: String, default: '' },
  area: { type: String, default: '' },
  postalCode: { type: String, default: '' },
  occupation: { type: String, default: '' },
  companyName: { type: String, default: '' },
  monthlyIncome: { type: Number, default: 0 },
  familyMembers: { type: Number, default: 1 },
  peopleInProperty: { type: Number, default: 1 },
  preferredMoveInDate: { type: Date, default: null },
  emergencyContactName: { type: String, default: '' },
  emergencyContactPhone: { type: String, default: '' },
  relationship: { type: String, default: '' },
  profileStatus: { type: String, default: 'Profile Incomplete' },
  propertyId: { type: String, default: '' },
  propertyName: { type: String, default: '' },
  propertyType: { type: String, default: '' },
  monthlyRent: { type: Number, default: 0 },
  rentalStartDate: { type: Date },
  rentalDurationMonths: { type: Number, default: 0 },
  applicationDate: { type: Date, default: Date.now },
  status: { type: String, default: 'Pending' },
  lastNotificationDate: { type: Date },
  nextNotificationDate: { type: Date },
  notes: { type: String, default: '' },
  archived: { type: Boolean, default: false },
}, { timestamps: true });

export default mongoose.model('RentalProfile', rentalProfileSchema, 'rental_profiles');
